### ISSUE TITLE
[REQUEST] 'Long' press event

### ISSUE THREAD

**Issue by Sneakpeakcss** [natural-harmonia-gropius/input-event#37]
Would it be possible to add an ability to split a single key into two different actions, depending on how long it's pressed for? Similar to how [mpv-pointer-event](https://github.com/christoph-heinrich/mpv-pointer-event) does it for mouse inputs.

**Comment by natural-harmonia-gropius** [comment]
https://github.com/natural-harmonia-gropius/input-event#press-to-speedup-release-to-restore

You can change SPACE in this example to MBTN_* and test is that works as your intended.

**Comment by Sneakpeakcss** [comment]
> https://github.com/natural-harmonia-gropius/input-event#press-to-speedup-release-to-restore
> 
> You can change SPACE in this example to MBTN_* and test is that works as your intended.

Huh, i could've swear that i've tried using it in this manner, but it didn't work for me. Either i got something wrong while defining `script-message-to` for it, or maybe got confused by the example and didn't notice the "restore" part, thinking that it only executes the command on key release.

```
h           script-message-to testscript command-one;show-text "first command"  	#@click
h           script-message-to testscript command-two;show-text "second command"  	#@press
h           ignore
```

Now it works how i needed it to, so thanks for pointing that out.
