### ISSUE TITLE
[Question] How to write ignore statement in json conf

### ISSUE THREAD

**Issue by verygoodlee** [natural-harmonia-gropius/input-event#38]
In this case, both `MBTN_LEFT double_click` in  json conf and `MBTN_LEFT_DBL` in input.conf have taken effect, double click cycle fullscreen twice.
```
# inputevent.conf
configs=~~/inputevent.json
```
```json
[
  {
    "key": "MBTN_LEFT",
    "on": {
      "click": "cycle pause",
      "double_click": "cycle fullscreen"
    }
  },
  {
    "key": "MBTN_LEFT_DBL",
    "on": {
    }
  }
]
```
```
# input.conf
MBTN_LEFT cycle pause
MBTN_LEFT_DBL cycle fullscreen
```
In general, json conf overrides input.conf for the same keys, but the `MBTN_LEFT_DBL` can't be ignored.

**Comment by verygoodlee** [comment]
maybe it's a mpv bug, `mp.add_forced_key_binding("MBTN_LEFT_DBL",...)` doesn't overwrite the user's custom bindings in input.conf.
```
#input.conf
MBTN_LEFT_DBL show-text 'aaa'
```
```lua
--test.lua
mp.add_forced_key_binding("MBTN_LEFT_DBL", "MBTN_LEFT_DBL", function() 
    mp.commandv("show-text", "bbb")
end)
```
![image](https://github.com/natural-harmonia-gropius/input-event/assets/45035465/4ad8979b-31ef-42b6-b70b-bd081212466f)
binding success, but still show 'aaa'

**Comment by natural-harmonia-gropius** [comment]
我的建议是不要绑定 `_DBL` , 逻辑上和 `@double_click` 冲突.
